"""This tests that large, commonly invoked departments continue to resolve
as we expect them. Any drift — changes to normalization, manual edits to
aliases, or tweaks in the resolver logic — will cause this test to fail.

To refresh the snapshot, edit the lists below by hand after confirming the
new behavior is intentional. The lists are *not* regenerated automatically,
and shouldn't be. The point is that they're static.
"""

import pytest

from gcorg_resolver.resolver import resolve

CANONICAL_ORGS_EN: list[tuple[str, int]] = [
    ("Agriculture and Agri-Food Canada", 2222),
    ("Canadian Heritage", 2223),
    ("Immigration, Refugees and Citizenship", 2224),
    ("IRCC", 2224),
    ("Department of Finance Canada", 2225),
    ("Finance", 2225),
    ("Fisheries and Oceans Canada", 2226),
    ("DFO", 2226),
    ("Global Affairs Canada", 2227),
    ("Health Canada", 2228),
    ("Employment and Social Development Canada", 2229),
    ("ESDC", 2229),
    ("Crown-Indigenous Relations and Northern Affairs Canada", 2230),
    ("Innovation, Science and Economic Development Canada", 2231),
    ("ISED", 2231),
    ("Department of Justice Canada", 2232),
    ("Justice", 2232),
    ("National Defence", 2233),
    ("DND", 2233),
    ("Natural Resources Canada", 2234),
    ("Public Safety Canada", 2235),
    ("Public Services and Procurement Canada", 2236),
    ("PSPC", 2236),
    ("Environment and Climate Change Canada", 2237),
    ("ECCC", 2237),
    ("Environment Canada", 2237),
    ("Transport Canada", 2238),
    ("Veterans Affairs Canada", 2239),
    ("PrairieCan", 2240),
    ("PrairiesCan", 2240),
    ("Prairies Economic Development Canada", 2240),
    ("Women and Gender Equality Canada", 2241),
    ("WAGE", 2241),
    ("Treasury Board of Canada Secretariat", 2242),
    ("TBS", 2242),
    ("Indigenous Services Canada", 2243),
    ("Atlantic Canada Opportunities Agency", 2244),
    ("Impact Assessment Agency of Canada", 2245),
    ("Canadian Grain Commission", 2246),
    ("Canadian Human Rights Commission", 2247),
    ("Canadian Intergovernmental Conference Secretariat", 2248),
    ("Canadian Northern Economic Development Agency", 2249),
    ("Canadian Security Intelligence Service", 2250),
    ("Canadian Space Agency", 2251),
    ("Canadian Transportation Agency", 2252),
    ("Communications Security Establishment Canada", 2253),
    ("CSE", 2253),
    ("Copyright Board Canada", 2254),
    ("Correctional Service Canada", 2255),
    ("Courts Administration Service", 2256),
    ("Canada Economic Development for Quebec Regions", 2257),
    ("Canada Ecomomic Development for Quebec Regions", 2257),
    ("Canada Ecomic Development for Quebec Regions", 2257),
    ("Federal Economic Development Agency for Southern Ontario", 2258),
    ("Financial Consumer Agency of Canada", 2259),
    ("Financial Transactions and Reports Analysis Centre of Canada", 2260),
    ("Immigration and Refugee Board of Canada", 2261),
    ("Library and Archives Canada", 2262),
    ("Military Grievances External Review Committee", 2263),
    ("Military Police Complaints Commission of Canada", 2264),
    ("Farm Products Council of Canada", 2265),
    ("National Film Board", 2266),
    ("Parole Board of Canada", 2267),
    ("Northern Pipeline Agency Canada", 2268),
    ("Housing, Infrastructure and Communities Canada", 2269),
    ("HICC", 2269),
    ("Office of the Auditor General of Canada", 2270),
    ("Elections Canada", 2271),
    ("Office of the Commissioner for Federal Judicial Affairs Canada", 2272),
    ("Office of the Commissioner of Lobbying of Canada", 2273),
    ("Office of the Commissioner of Official Languages", 2274),
    ("Office of the Intelligence Commissioner", 2275),
    ("The Correctional Investigator Canada", 2276),
    ("Public Prosecution Service of Canada", 2277),
    ("Office of the Secretary to the Governor General", 2278),
    ("Office of the Public Sector Integrity Commissioner of Canada", 2279),
    ("Office of the Superintendent of Financial Institutions Canada", 2280),
    ("Office of the Information Commissioner of Canada", 2281),
    ("Office of the Privacy Commissioner of Canada", 2282),
    ("Patented Medicine Prices Review Board Canada", 2283),
    ("Privy Council Office", 2284),
    ("Public Health Agency of Canada", 2285),
    ("Public Service Commission of Canada", 2286),
    ("Registrar of the Supreme Court of Canada", 2287),
    ("Royal Canadian Mounted Police", 2288),
    ("RCMP External Review Committee", 2289),
    ("Civilian Review and Complaints Commission for the RCMP", 2290),
    ("National Security and Intelligence Review Agency Secretariat", 2291),
    (
        "National Security and Intelligence Review Agency",
        3579,
    ),  # These are apparently different
    ("Shared Services Canada", 2292),
    ("Statistics Canada", 2293),
    ("StatsCan", 2293),
    ("SC", None),  # Shouldn't match, is it StatsCan or Service Canada?
    ("Veterans Review and Appeal Board", 2294),
    ("Leaders’ Debates Commission", 2296),
    ("Administrative Tribunals Support Service of Canada", 2297),
    ("Pacific Economic Development Canada", 2298),
    ("Federal Economic Development Agency for Northern Ontario", 2299),
    ("Canada Border Services Agency", 2300),
    ("Canada Emission Reduction Incentives Agency", 2301),
    ("Canada Employment Insurance Commission", 2302),
    ("Canada Revenue Agency", 2303),
    ("CRA", 2303),
    ("Canada School of Public Service", 2304),
    ("CSPS", 2304),
    ("Canadian Centre for Occupational Health and Safety", 2305),
    ("Canadian Food Inspection Agency", 2306),
    ("CFIA", 2306),
    ("Canadian Institutes of Health Research", 2307),
    ("Canadian Nuclear Safety Commission", 2308),
    ("Transportation Safety Board of Canada", 2309),
    ("Law Commission of Canada", 2310),
    ("The National Battlefields Commission", 2311),
    ("Canada Energy Regulator", 2312),
    ("National Research Council Canada", 2313),
    ("Natural Sciences and Engineering Research Council of Canada", 2314),
    ("NSERC", 2314),
    ("Parks Canada", 2315),
    ("Parks", 2315),
    ("Social Sciences and Humanities Research Council of Canada", 2316),
    ("Invest in Canada Hub", 2317),
    ("Polar Knowledge Canada", 2318),
    ("POLAR", 2318),
    ("Accessibility Standards Canada", 2319),
    ("Canadian Radio-television and Telecommunications Commission", 2396),
    ("CRTC", 2396),
]


CANONICAL_ORGS_FR: list[tuple[str, int]] = [
    ("Agriculture et Agroalimentaire Canada", 2222),
    ("Patrimoine canadien", 2223),
    ("Immigration, Réfugiés et Citoyenneté Canada", 2224),
    ("Ministère des Finances Canada", 2225),
    ("Pêches et Océans Canada", 2226),
    ("Affaires mondiales Canada", 2227),
    ("Santé Canada", 2228),
    ("Emploi et Développement social Canada", 2229),
    ("Relations Couronne-Autochtones et Affaires du Nord Canada", 2230),
    ("Innovation, Sciences et Développement économique Canada", 2231),
    ("Ministère de la Justice Canada", 2232),
    ("Défense nationale", 2233),
    ("Ressources naturelles Canada", 2234),
    ("Sécurité publique Canada", 2235),
    ("Services publics et Approvisionnement Canada", 2236),
    ("Environnement et Changement climatique Canada", 2237),
    ("Transports Canada", 2238),
    ("Anciens Combattants Canada", 2239),
    ("Développement économique Canada pour les Prairies", 2240),
    ("Femmes et Égalité des genres Canada", 2241),
    ("Secrétariat du Conseil du Trésor du Canada", 2242),
    ("Services aux Autochtones Canada", 2243),
    ("Agence de promotion économique du Canada atlantique", 2244),
    ("Agence d'évaluation d'impact du Canada", 2245),
    ("Commission canadienne des grains", 2246),
    ("Commission canadienne des droits de la personne", 2247),
    ("Secrétariat des conférences intergouvernementales canadiennes", 2248),
    ("Agence canadienne de développement économique du Nord", 2249),
    ("Service canadien du renseignement de sécurité", 2250),
    ("Agence spatiale canadienne", 2251),
    ("Office des transports du Canada", 2252),
    ("Centre de la sécurité des télécommunications Canada", 2253),
    ("Commission du droit d'auteur Canada", 2254),
    ("Service correctionnel Canada", 2255),
    ("SCC", 2255),
    ("Service administratif des tribunaux judiciaires", 2256),
    ("Développement économique Canada pour les régions du Québec", 2257),
    ("Agence fédérale de développement économique pour le Sud de l'Ontario", 2258),
    ("Agence de la consommation en matière financière du Canada", 2259),
    ("Centre d'analyse des opérations et déclarations financières du Canada", 2260),
    ("Commission de l'immigration et du statut de réfugié du Canada", 2261),
    ("Bibliothèque et Archives Canada", 2262),
    ("Comité externe d'examen des griefs militaires", 2263),
    ("Commission d'examen des plaintes concernant la police militaire du Canada", 2264),
    ("Conseil des produits agricoles du Canada", 2265),
    ("Office national du film", 2266),
    ("Commission des libérations conditionnelles du Canada", 2267),
    ("Administration du pipe-line du Nord Canada", 2268),
    ("Logement, Infrastructures et Collectivités Canada", 2269),
    ("Bureau du vérificateur général du Canada", 2270),
    ("Élections Canada", 2271),
    ("Commissariat à la magistrature fédérale Canada", 2272),
    ("Commissariat au lobbying du Canada", 2273),
    ("Commissariat aux langues officielles", 2274),
    ("Bureau du commissaire au renseignement", 2275),
    ("L'Enquêteur correctionnel Canada", 2276),
    ("Service des poursuites pénales du Canada", 2277),
    ("Bureau du secrétaire du gouverneur général", 2278),
    ("Commissariat à l'intégrité du secteur public du Canada", 2279),
    ("Bureau du surintendant des institutions financières Canada", 2280),
    ("Commissariat à l'information au Canada", 2281),
    ("Commissariat à la protection de la vie privée du Canada", 2282),
    ("Conseil d'examen du prix des médicaments brevetés Canada", 2283),
    ("Bureau du Conseil privé", 2284),
    ("Agence de la santé publique du Canada", 2285),
    ("Commission de la fonction publique du Canada", 2286),
    ("Registraire de la Cour suprême du Canada", 2287),
    ("Gendarmerie royale du Canada", 2288),
    ("Comité externe d'examen de la GRC", 2289),
    (
        "Commission civile d'examen et de traitement des plaintes relatives à la GRC",
        2290,
    ),
    (
        "Secrétariat de l’Office de surveillance des activités en matière de sécurité nationale et de renseignement",
        2291,
    ),
    ("Services partagés Canada", 2292),
    ("Statistique Canada", 2293),
    ("Tribunal des anciens combattants (révision et appel)", 2294),
    (
        "Secrétariat du Comité des parlementaires sur la sécurité nationale et le renseignement",
        2295,
    ),
    ("Commission des débats des chefs", 2296),
    ("Service canadien d'appui aux tribunaux administratifs", 2297),
    ("Développement économique Canada pour le Pacifique", 2298),
    ("Agence fédérale de développement économique pour le Nord de l'Ontario", 2299),
    ("Agence des services frontaliers du Canada", 2300),
    ("Agence canadienne pour l'incitation à la réduction des émissions", 2301),
    ("Commission de l'assurance-emploi du Canada", 2302),
    ("Agence du revenu du Canada", 2303),
    ("École de la fonction publique du Canada", 2304),
    ("Centre canadien d’hygiène et de sécurité au travail", 2305),
    ("Centre canadien d'hygiène et de sécurité au travail", 2305),
    ("Agence canadienne d'inspection des aliments", 2306),
    ("Instituts de recherche en santé du Canada", 2307),
    ("Commission canadienne de sûreté nucléaire", 2308),
    ("Bureau de la sécurité des transports du Canada", 2309),
    ("Commission du droit du Canada", 2310),
    ("Commission des champs de bataille nationaux", 2311),
    ("Régie de l'énergie du Canada", 2312),
    ("Conseil national de recherches Canada", 2313),
    ("Conseil de recherches en sciences naturelles et en génie du Canada", 2314),
    ("Parcs Canada", 2315),
    ("Parcs", 2315),
    ("Conseil de recherches en sciences humaines du Canada", 2316),
    ("Investir au Canada", 2317),
    ("Savoir polaire Canada", 2318),
    ("Normes d'accessibilité Canada", 2319),
    ("Conseil de la radiodiffusion et des télécommunications canadiennes", 2396),
]

# These are bilingual acronym pairs that should resolve the same always.
# These are commonly used in ECM products.

BILINGUAL_ACRONYMS: list[tuple[str, int]] = [
    ("CRA / ARC", 2303),
    ("IRCC / IRCC", 2224),
    ("ESDC / EDSC", 2229),
    ("RCMP / GRC", 2288),
    ("PC / PC", 2315),
    ("ISED / ISDE", 2231),
    ("CBSA / ASFC", 2300),
    ("TC / TC", 2238),
    ("VAC / ACC", 2239),
    ("TBS / SCT", 2242),
    ("NRCan / RNCan", 2234),
    ("DND / MDN", 2233),
    ("PCH / PCH", 2223),
    ("DFO / MPO", 2226),
    ("PSPC / SPAC", 2236),
    ("CFIA / ACIA", 2306),
    ("GAC / AMC", 2227),
    ("ECCC / ECCC", 2237),
    ("PS / SP", 2235),
    ("HC / SC", 2228),
    ("IRB / CISR", 2261),
    ("AAFC / AAC", 2222),
    ("CDC / CCL", 3615),
    ("LAC / BAC", 2262),
    ("CSC / SCC", 2255),
    ("CRTC / CRTC", 2396),
    ("ACOA / APECA", 2244),
    ("SSC / SPC", 2292),
    ("PSC / CFP", 2286),
    ("CER / REC", 2312),
    ("IAAC / AEIC", 2245),
    ("StatCan / StatCan", 2293),
    ("WD / DEO", 2240),
    ("CNSC / CCSN", 2308),
    ("JUS / JUS", 2232),
    ("CGC / CCG", 2246),
    ("ATSSC / SCDATA", 2297),
    ("ISC / SAC", 2243),
    ("WAGE / FEGC", 2241),
]

GC_EMAILS: list[tuple[str, int]] = [
    ("noreply.demo@accessibilite.canada.ca", 2319),
    ("sample.user@accessible.canada.ca", 2319),
    ("example.user@acfc.gc.ca", 2259),
    ("fictitious@acls-aatc.ca", 3438),
    ("sample.user@acsta.gc.ca", 3655),
    ("noreply.demo@adb.org", 3400),
    ("not.real@admtl.com", 3436),
    ("test.account@aecl.ca", 3649),
    ("demo.account@aeroportdequebec.com", 3435),
    ("fake.contact@afdb.org", 3399),
    ("sample.inbox@agr.gc.ca", 2222),
    ("example.user@aiib.org", 3414),
    ("demo.user@asc-csa.gc.ca", 2251),
    ("noreply.demo@asfc.gc.ca", 2300),
    ("fake.inbox@asiapacific.ca", 3437),
    ("fake.contact@atlanticpilotage.com", 3654),
    ("fake.contact@bank-banque-canada.ca", 3633),
    ("sample.inbox@bankofcanada.ca", 3633),
    ("test.account@bdc.ca", 3646),
    ("mock.email@beaux-arts.ca", 3626),
    ("sample.inbox@bibliotheque-archives.canada.ca", 2262),
    ("fake.user@bst-tsb.gc.ca", 2309),
    ("fake.address@cadth.ca", 3450),
    ("testing123@canadacouncil.ca", 3618),
    ("dummy.account@canadagames.ca", 3445),
    ("noreply.demo@canadapost.ca", 3651),
    ("example.user@canafe-fintrac.gc.ca", 2260),
    ("testing123@CanNor.gc.ca", 2249),
    ("demo.user@caribank.org", 3401),
    ("dummy.account@cas-satj.gc.ca", 2256),
    ("fake.inbox@catsa.gc.ca", 3655),
    ("not.real@cb-cda.gc.ca", 2254),
    ("demo.user@cbc.radio-canada.ca", 3619),
    ("not.real@cbsa.gc.ca", 2300),
    ("fictitious@ccbn-nbc.gc.ca", 2311),
    ("fake.address@ccc.ca", 3639),
    ("fake.contact@ccdp-chrc.gc.ca", 2247),
    ("noreply.demo@ccg-gcc.gc.ca", 3533),
    ("mock.email@cchst.ca", 2305),
    ("sample.user@ccn-ncc.gc.ca", 3653),
    ("noreply.demo@ccn.ca", 3648),
    ("example.user@ccohs.ca", 2305),
    ("fictitious@ccsa.ca", 3451),
    ("dummy.mail@cdc-ccl.gc.ca", 3615),
    ("sample.inbox@cdc-dcc.gc.ca", 3652),
    ("example.user@cdev.gc.ca", 3635),
    ("example.user@cdic.ca", 3634),
    ("demo.account@cec.org", 3412),
    ("fake.contact@cer-rec.gc.ca", 2312),
    ("sample.user@ceri.ca", 3452),
    ("fake.user@cfc-swc.gc.ca", 2241),
    ("fake.address@cfhi-fcass.ca", 3516),
    ("testing123@cfta-alec.ca", 3471),
    ("not.real@chrc-ccdp.gc.ca", 2247),
    ("example.user@cihi.ca", 3453),
    ("noreply.demo@cihr-irsc.gc.ca", 2307),
    ("fake.inbox@cipo.gc.ca", 3537),
    ("placeholder@cisr-irb.gc.ca", 2261),
    ("demo.account@clc-sic.ca", 3650),
    ("placeholder@clrc.ca", 3454),
    ("fake.address@cmf-fmc.ca", 3447),
    ("pretend.user@cmhc.ca", 3631),
    ("dummy.mail@cna-nac.ca", 3625),
    ("example.user@cnsc-ccsn.gc.ca", 2308),
    ("mock.email@cnsoer.ca", 3449),
    ("sample.inbox@coach.ca", 3459),
    ("dummy.account@commissionsantementale.ca", 3475),
    ("example.user@conseildesarts.ca", 3618),
    ("noreply.demo@cpma-acpm.agr.gc.ca", 2222),
    ("noreply.demo@cppib.com", 3636),
    ("fictitious@crcc-ccetp.gc.ca", 2290),
    ("demo.account@crdi.ca", 3641),
    ("sample.user@crdsc-sdrcc.ca", 3498),
    ("test.user@crr.ca", 3624),
    ("fake.user@crrf-fcrr.ca", 3624),
    ("not.real@crtc.gc.ca", 2396),
    ("dummy.account@cse-cst.gc.ca", 2253),
    ("noreply.demo@csiontario.ca", 3457),
    ("test.account@csps-efpc.gc.ca", 2304),
    ("noreply.demo@cyqm.ca", 3465),
    ("testing123@dcc-cdc.gc.ca", 3652),
    ("sample.user@debates-debats.ca", 2296),
    ("fake.contact@dfo-mpo.gc.ca", 2226),
    ("mock.email@downsviewpark.ca", 3690),
    ("dummy.account@drdc-rddc.gc.ca", 3540),
    ("pretend.user@droitsdelapersonne.ca", 3620),
    ("dummy.mail@ebrd.com", 3402),
    ("dummy.account@edc.ca", 3640),
    ("fake.address@edsc.gc.ca", 2302),
    ("fake.contact@elections.ca", 2271),
    ("sample.inbox@erc-cee.gc.ca", 2289),
    ("noreply.demo@esdc.gc.ca", 2302),
    ("example.user@fcac.gc.ca", 2259),
    ("dummy.account@fcass-cfhi.ca", 3516),
    ("fake.contact@fcc-fac.ca", 3616),
    ("sample.inbox@fdr.net", 3492),
    ("mock.email@feddevontario.gc.ca", 2258),
    ("fake.inbox@federalbridge.ca", 3661),
    ("fake.address@fednor.gc.ca", 2299),
    ("pretend.user@fintrac-canafe.gc.ca", 2260),
    ("placeholder@fja-cmf.gc.ca", 2272),
    ("placeholder@flyeia.com", 3461),
    ("demo.user@flylondon.ca", 3464),
    ("test.account@flypei.com", 3458),
    ("not.real@fondationtrudeau.ca", 3484),
    ("sample.inbox@forces.gc.ca", 2233),
    ("dummy.mail@fpcc-cpac.gc.ca", 2265),
    ("dummy.mail@frederictonairport.ca", 3462),
    ("fake.user@freshwaterfish.com", 3638),
    ("sample.user@gallery.ca", 3626),
    ("mock.email@ganderairport.com", 3463),
    ("fictitious@gg.ca", 2278),
    ("not.real@glpa-apgl.com", 3656),
    ("dummy.account@gnb.ca", 3474),
    ("fake.user@gordiehoweinternationalbridge.com", 3644),
    ("noreply.demo@grainscanada.gc.ca", 2246),
    ("dummy.mail@greatlakes-seaway.com", 3501),
    ("noreply.demo@healthcareexcellence.ca", 3517),
    ("not.real@hfr-tgf.ca", 3707),
    ("fictitious@hiaa.ca", 3467),
    ("not.real@historymuseum.ca", 3621),
    ("demo.account@housing-infrastructure.canada.ca", 2269),
    ("mock.email@humanrights.ca", 3620),
    ("dummy.account@iadb.org", 3403),
    ("example.user@ic.gc.ca", 2231),
    ("demo.user@icis.ca", 3453),
    ("example.user@idrc.ca", 3641),
    ("pretend.user@ifc.org", 3406),
    ("fake.contact@infoway-inforoute.ca", 3446),
    ("fake.address@infrastructure.gc.ca", 3642),
    ("pretend.user@ingeniumcanada.org", 3627),
    ("example.user@innovation.ca", 3443),
    ("test.user@inspection.gc.ca", 2306),
    ("pretend.user@insquebec.org", 3470),
    ("example.user@international.gc.ca", 2227),
    ("fake.inbox@investpsp.ca", 3663),
    ("fake.address@irb-cisr.gc.ca", 2261),
    ("test.account@irsc-cihr.gc.ca", 2307),
    ("example.user@jacquescartierchamplain.ca", 3643),
    ("placeholder@justice.gc.ca", 2232),
    ("fake.contact@library-archives.canada.ca", 2262),
    ("not.real@lobbycanada.gc.ca", 2273),
    ("fake.contact@lwcb.ca", 3473),
    ("placeholder@marine-atlantic.ca", 3658),
    ("fake.user@mentalhealthcommission.ca", 3475),
    ("example.user@miga.org", 3411),
    ("demo.account@mint.ca", 3637),
    ("not.real@monnaie.ca", 3637),
    ("fake.user@mpcc-cppm.gc.ca", 2264),
    ("fake.address@museedelhistoire.ca", 3621),
    ("fictitious@nac-cna.ca", 3625),
    ("not.real@nature.ca", 3623),
    ("demo.account@navcanada.ca", 3480),
    ("example.user@ncc-ccn.gc.ca", 3653),
    ("mock.email@northern-pipeline.canada.ca", 2268),
    ("dummy.account@npa.ca", 3478),
    ("pretend.user@nrc.canada.ca", 2313),
    ("dummy.account@nrcan-rncan.gc.ca", 2234),
    ("sample.user@nserc-crsng.gc.ca", 2314),
    ("demo.user@nsicop-cpsnr.ca", 2295),
    ("noreply.demo@nsira-ossnr.gc.ca", 3579),
    ("sample.inbox@oci-bec.gc.ca", 2276),
    ("demo.account@officiallanguages.gc.ca", 2274),
    ("sample.user@oic-ci.gc.ca", 2281),
    ("mock.email@opic.gc.ca", 3537),
    ("sample.user@osfi-bsif.gc.ca", 2280),
    ("fake.user@otc-cta.gc.ca", 2252),
    ("mock.email@ouranos.ca", 3483),
    ("noreply.demo@p3canada.ca", 3645),
    ("demo.user@parcdownsview.ca", 3690),
    ("demo.account@parl.gc.ca", 3584),
    ("fake.user@partenariatcontrelecancer.ca", 3455),
    ("testing123@partnershipagainstcancer.ca", 3455),
    ("fake.inbox@patientsafetyinstitute.ca", 3456),
    ("fake.address@pbo-dpb.gc.ca", 3433),
    ("dummy.mail@pc.gc.ca", 2315),
    ("pretend.user@pcmb.ca", 3485),
    ("fake.contact@pco-bcp.gc.ca", 2284),
    ("placeholder@peacebridge.com", 3440),
    ("fake.contact@pgairport.ca", 3488),
    ("placeholder@pgic-iogc.gc.ca", 3541),
    ("test.account@phac-aspc.gc.ca", 2285),
    ("dummy.account@pier21.ca", 3622),
    ("dummy.account@pilotagestlaurent.gc.ca", 3657),
    ("dummy.account@pipe-line-nord.canada.ca", 2268),
    ("sample.inbox@port-montreal.com", 3477),
    ("fake.user@portalberniportauthority.ca", 3486),
    ("fake.user@portmetrovancouver.com", 3509),
    ("pretend.user@portofbelledune.ca", 3439),
    ("demo.user@portofhalifax.ca", 3468),
    ("sample.inbox@portofoshawa.ca", 3481),
    ("fake.user@portofthunderbay.com", 3504),
    ("dummy.mail@portquebec.ca", 3490),
    ("test.user@portsaguenay.ca", 3493),
    ("placeholder@portsi.com", 3497),
    ("demo.user@portstoronto.com", 3506),
    ("demo.account@porttr.com", 3507),
    ("test.account@portwindsor.com", 3514),
    ("fictitious@postescanada.ca", 3651),
    ("fake.address@ppa.gc.ca", 3659),
    ("noreply.demo@ppsc-sppc.gc.ca", 2277),
    ("demo.user@priv.gc.ca", 2282),
    ("sample.inbox@psic-ispc.gc.ca", 2279),
    ("noreply.demo@publicsafety.gc.ca", 2235),
    ("fake.contact@quai21.ca", 3622),
    ("dummy.account@rcmp-grc.gc.ca", 2288),
    ("testing123@rcneee.ca", 3449),
    ("fake.address@rti.ca", 3660),
    ("testing123@rupertport.com", 3489),
    ("placeholder@sadc.ca", 3634),
    ("testing123@saintjohnairport.com", 3494),
    ("pretend.user@scc-csc.ca", 2287),
    ("noreply.demo@scc.ca", 3648),
    ("demo.account@schl.ca", 3631),
    ("example.user@scics.ca", 2248),
    ("dummy.account@sdtc.ca", 3444),
    ("sample.inbox@securitepublique.gc.ca", 2235),
    (
        "noreply.demo@sen.parl.gc.ca",
        3584,
    ),  # This is only half right, but we only use parl.gc.ca and don't dive into sub-subdomains
    ("demo.user@sjport.com", 3495),
    ("sample.user@sshrc-crsh.gc.ca", 2316),
    ("dummy.account@statcan.gc.ca", 2293),
    ("fake.user@swc-cfc.gc.ca", 2241),
    ("mock.email@tc.gc.ca", 2238),
    ("testing123@telefilm.ca", 3629),
    ("dummy.account@terryfoxawards.ca", 3502),
    ("fake.contact@tgf-hfr.ca", 3707),
    ("test.account@theforks.com", 3416),
    ("fictitious@torontopearson.com", 3466),
    ("fake.address@tpsgc-pwgsc.gc.ca", 2236),
    ("dummy.mail@trudeaufoundation.ca", 3484),
    ("sample.inbox@tsb-bst.gc.ca", 2309),
    ("fake.inbox@tv5.ca", 3508),
    ("test.account@veterans.gc.ca", 2239),
    ("example.user@viarail.ca", 3662),
    ("sample.user@victoriaairport.com", 3511),
    ("test.user@vrab-tacra.gc.ca", 2294),
    ("example.user@waa.ca", 3515),
    ("test.account@wada-ama.org", 3413),
    ("test.user@waterfrontoronto.ca", 3512),
    ("example.user@whc.org", 3513),
    ("placeholder@winsport.ca", 3442),
    ("test.user@yow.ca", 3482),
    ("testing123@yqr.ca", 3491),
    ("sample.inbox@yvr.ca", 3510),
    ("not.real@yxe.ca", 3496),
    ("fake.contact@yyc.com", 3441),
    ("not.real@banquemondiale.org", None),
    ("fake.email@canada.gc.ca", None),  # These are ambiguous and shouldn't resolve
    ("not.real@canada.ca", None),
    ("fake.contact@ijc.org", None),
    ("dummy.account@imf.org", None),
    ("example.user@worldbank.org", None),  # Too ambiguous despite showing up in source
]


@pytest.mark.parametrize(("name", "expected_id"), CANONICAL_ORGS_EN)
def test_canonical_english_name_resolves(name: str, expected_id: int):
    assert resolve(name) == expected_id


@pytest.mark.parametrize(("name", "expected_id"), CANONICAL_ORGS_FR)
def test_canonical_french_name_resolves(name: str, expected_id: int):
    assert resolve(name) == expected_id


@pytest.mark.parametrize(("name", "expected_id"), BILINGUAL_ACRONYMS)
def test_bilingual_acronym_resolves(name: str, expected_id: int):
    assert resolve(name) == expected_id


@pytest.mark.parametrize(("name", "expected_id"), GC_EMAILS)
def test_emails_resolves(name: str, expected_id: int):
    assert resolve(name) == expected_id
